import { axiosBaseQuery } from "@/src/shared/utitlity/axios-base-query";
import { createApi } from "@reduxjs/toolkit/query/react";

export const appApi = createApi({
  reducerPath: "appApi",
  baseQuery: axiosBaseQuery(),
  tagTypes: [
    "Users",
    "UserInfo",
    "Properties",
    "PropertyInfo",
    "Tenants",
    "TenantInfo",
    "Rooms",
    "Leases",
    "BankAccounts",
    "BankAccountInfo",
    "RevenueTypes",
    "RevenueTypeInfo",
    "DocumentTypes",
    "DocumentTypeInfo",
    "ExpenseTypes",
    "ExpenseTypeInfo",
    "OrganizationBankAccounts",
    "OrganizationBankAccountInfo",
    "Departments",
    "DepartmentInfo",
    "LeaseInfo",
    "Expenses",
    "ExpenseInfo",
    "InvoiceItems",
    "InvoiceItemInfo",
    "EmergencyContacts",
    "EmergencyContactInfo",
    "Payables",
    "PayableInfo",
    "Receivables",
    "ReceivableInfo",
    "MaintenanceRequests",
    "MaintenanceRequestInfo",
  ],
  endpoints: () => ({}),
});
